### ISSUE TITLE
This is an outstanding, practical walkthru

### ISSUE THREAD

**Issue by weisisheng** [aws-samples/serverless-account-signup-service#2]
of the various choices throughout the state machine steps.  One of the best I have seen in 12+ months.  Kudos!

**Comment by dmahapatro** [comment]
Thank you @weisisheng for the comment.

**Comment by dmahapatro** [comment]
@weisisheng FYI ... There are new intrinsic functions that were recently added to AWS Step Functions. https://aws.amazon.com/blogs/compute/introducing-new-intrinsic-functions-for-aws-step-functions/

I believe it will be useful for you too.
